### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Data/NYU/train/joint_data.mat'

### ISSUE THREAD

**Issue by kingsman0000** [IcarusWizard/PixelwiseRegression#1]
Hello!How can I fix this Error as title?
I'm already download the NYU dataset and pretrain model(NYU_default_final.pt) but I confuse how can I get joint_data.mat?Thanks!

**Comment by IcarusWizard** [comment]
Hi. What do you have currently under `Data/NYU`?  
Note you need to extract the NYU dataset to `Data/NYU`. By default, the extraction will create a folder called `dataset`, and you need to move everything in that folder to `Data/NYU`.

**Comment by kingsman0000** [comment]
It only has test and train folder (image)instead of joint_data.mat.How can I get joint_data.mat?
Do I need to run something to generate this .mat file?thanks

**Comment by IcarusWizard** [comment]
That is weird. It does have the `joint_data.mat` inside the `train` and `test` folder. Where do you get the dataset? 
For reference, I downloaded it from [here](https://jonathantompson.github.io/NYU_Hand_Pose_Dataset.htm#download).

**Comment by kingsman0000** [comment]
Thanks for your help.I finally find it .Furthermore,may I know how to visualize result or images?
In the which file did you mention?Thanks.

**Comment by IcarusWizard** [comment]
To visualize plots, you need to use [Awesome Hand Pose Estimation](https://github.com/xinghaochen/awesome-hand-pose-estimation).
To visualize images and skeletons, you can use `test_samples.py`. For example, `python test_samples.py --dataset NYU`.

**Comment by kingsman0000** [comment]
It works!Thanks very much for your help.
