### ISSUE TITLE
a naive question about error

### ISSUE THREAD

**Issue by donghai-x** [IcarusWizard/PixelwiseRegression#2]
Hello, thanks for your work, in the paper you said ''Note that, we do not use XYZ coordinates as output like some models did, because the UVD coordinates are more direct information from depthimages without a transformation influenced by the intrinsicparameters of the camera'', so, when you compute the 3D error, you uesd UVD coordinates or XYZ coordinates ?

**Comment by IcarusWizard** [comment]
Hi. Sorry for your confusion. 

When computing loss to train the network, we use UVD coordinates to avoid the affect of intrinsic parameters of the camera. When reporting 3D error, the outputs of the network are covered back to XYZ coordinates.

**Comment by donghai-x** [comment]
Thank you very much
