### ISSUE TITLE
Why is the heatmap generated like this?

### ISSUE THREAD

**Issue by chi-gao123** [IcarusWizard/PixelwiseRegression#5]
When I look at the source code, it is difficult to understand why it is designed this way, colud you please explain it, thank you very much~
""""
min_d = max(du + dv - 1, 0)
max_d = min(du, dv)
d = (max_d + min_d) / 2
b = du - d
c = dv - d
a = 1 + d - du - dv

heatmap[low_v, low_u] = a
heatmap[low_v, low_u + 1] = b
heatmap[low_v + 1, low_u] = c
heatmap[low_v + 1, low_u + 1] = d"""

**Comment by IcarusWizard** [comment]
Hi @chi-gao123. Thanks for your question.

The whole point of the heatmap generation is to represent it as a probability map of the joint position. That is if we take the expectation over the heatmap to the coordinates, we should recover the true joint position. For simplicity, we only consider the four adjacent pixels (later a Gaussian kernel is applied to enlarge the field). However, taking an expectation over `u` and `v` only gives two conditions, and the solution is not determined. Additionally, we have the constrain of probability function of summation to 1 and non-negative. Combining these conditions, we have a bounded solution set. Then we simply take the middle value of the solution set to generate the heatmap.

The below picture is the solving process. 

![image](https://user-images.githubusercontent.com/13862360/163855043-ba0f5bbb-fd3b-43b3-bfe5-096625f35b7f.png)
