### ISSUE TITLE
X_center_test.txt file

### ISSUE THREAD

**Issue by nasif-raihan** [IcarusWizard/PixelwiseRegression#7]
Hi there, can you please suggest how can i generate _X_center_test.txt_ file to infer on a custom 2D hand image?

**Comment by IcarusWizard** [comment]
Hi, thanks for your question. These files are copied from the [V2V-Pose repo](https://github.com/mks0601/V2V-PoseNet_RELEASE#results). As far as I know, they train a DeepPrior++ network to extract those centre positions.

**Comment by nasif-raihan** [comment]
Thank you for your quick response!
