### ISSUE TITLE
FileNotFoundError: Data/MSRA/P1/5/joint.txt not found.

### ISSUE THREAD

**Issue by mamuncseru** [IcarusWizard/PixelwiseRegression#8]
After extracting MSRA dataset, everything is availabe but this file Data/MSRA/P1/5/joint.txt not found. Where can I find this file

**Comment by IcarusWizard** [comment]
Hi, I check the dataset and the file is right there. Could you please follow the instruction [here](https://github.com/IcarusWizard/PixelwiseRegression#msra) and make sure you download the correct dataset and extract it to the correct place?

**Comment by mamuncseru** [comment]
![image](https://github.com/IcarusWizard/PixelwiseRegression/assets/43672817/2463055d-4974-4bfc-8280-768e3e6767b0)
This is the situation. Couple of files found correctly when iterating then it stopped on this specific file. I downloaded the zipped file from the link there provided.  Okay, I will extract again. Thank you for quick response and I will let you know.

**Comment by IcarusWizard** [comment]
By just a quick look, the file definitely has some problem. The MSRA dataset have 9 subjects P0 - P8, but only 7 are in your folder.

**Comment by mamuncseru** [comment]
you are right. Thanks. I noticed when I moved data from one directory to another directory, it corrupted. Thanks again.
